image: node:18
pipelines:
  default:
    - step:
        runs-on:
          - self.hosted
          - linux
        name: yarn-build
        script:
          - git submodule sync
          - git submodule update --init --recursive
          - apt-get update && apt-get install -y openjdk-17-jdk
          - cd baserepo
          - yarn 
          - yarn build
