image: atlassian/default-image:4
pipelines:
  default:
    - step:
        name: yarn-build
        script:
          - git submodule sync
          - git submodule update --init --recursive
          - npm install --global yarn
          - sudo apt-get update && apt-get install -y openjdk-17-jdk
          - cd baserepo
          - yarn 
          - yarn build
