version: 2.1
orbs:
  node: circleci/node@4.7

jobs:
  yarn-build:
    docker:
      - image: cimg/openjdk:17.0-node
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run:
          name: "yarn-build"
          command: |
            cd baserepo
            yarn
            yarn build
workflows:
  yarn-build-workflow:
    jobs:
      - yarn-build