build:
  image: node:latest
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - cd baserepo
    - apt-get update && apt-get install -y openjdk-17-jdk 
    - yarn
    - yarn build
  rules:
    - if: $ENABLE_PIPELINES == "true"
