build:
  image: node:latest
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - cd baserepo
    - sudo apt-get update && sudo apt-get install -y openjdk-17-jdk 
    - yarn
    - yarn build
